//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::GUI::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::GUI::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->ResetButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ResetButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::BRESET_Click);
        }
        break;
    case 3:
        {
            this->ShuffleButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->ShuffleButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::BSHUFFLE_Click);
        }
        break;
    case 4:
        {
            this->B0_4 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B0_4))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B0_4_Click);
        }
        break;
    case 5:
        {
            this->B1_4 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B1_4))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B1_4_Click);
        }
        break;
    case 6:
        {
            this->B2_4 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B2_4))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B2_4_Click);
        }
        break;
    case 7:
        {
            this->B3_4 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B3_4))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B3_4_Click);
        }
        break;
    case 8:
        {
            this->B4_4 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B4_4))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B4_4_Click);
        }
        break;
    case 9:
        {
            this->B0_3 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B0_3))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B0_3_Click);
        }
        break;
    case 10:
        {
            this->B1_3 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B1_3))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B1_3_Click);
        }
        break;
    case 11:
        {
            this->B2_3 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B2_3))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B2_3_Click);
        }
        break;
    case 12:
        {
            this->B3_3 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B3_3))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B3_3_Click);
        }
        break;
    case 13:
        {
            this->B4_3 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B4_3))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B4_3_Click);
        }
        break;
    case 14:
        {
            this->B0_2 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B0_2))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B0_2_Click);
        }
        break;
    case 15:
        {
            this->B1_2 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B1_2))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B1_2_Click);
        }
        break;
    case 16:
        {
            this->B2_2 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B2_2))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B2_2_Click);
        }
        break;
    case 17:
        {
            this->B3_2 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B3_2))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B3_2_Click);
        }
        break;
    case 18:
        {
            this->B4_2 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B4_2))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B4_2_Click);
        }
        break;
    case 19:
        {
            this->B0_1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B0_1))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B0_1_Click);
        }
        break;
    case 20:
        {
            this->B1_1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B1_1))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B1_1_Click);
        }
        break;
    case 21:
        {
            this->B2_1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B2_1))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B2_1_Click);
        }
        break;
    case 22:
        {
            this->B3_1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B3_1))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B3_1_Click);
        }
        break;
    case 23:
        {
            this->B4_1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B4_1))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B4_1_Click);
        }
        break;
    case 24:
        {
            this->B0_0 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B0_0))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B0_0_Click);
        }
        break;
    case 25:
        {
            this->B1_0 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B1_0))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B1_0_Click);
        }
        break;
    case 26:
        {
            this->B2_0 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B2_0))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B2_0_Click);
        }
        break;
    case 27:
        {
            this->B3_0 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B3_0))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B3_0_Click);
        }
        break;
    case 28:
        {
            this->B4_0 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->B4_0))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::GUI::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::B4_0_Click);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::GUI::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


