#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Button;
            }
        }
    }
}

namespace GUI
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Controls::Button^ ResetButton;
        private: ::Windows::UI::Xaml::Controls::Button^ ShuffleButton;
        private: ::Windows::UI::Xaml::Controls::Button^ B0_4;
        private: ::Windows::UI::Xaml::Controls::Button^ B1_4;
        private: ::Windows::UI::Xaml::Controls::Button^ B2_4;
        private: ::Windows::UI::Xaml::Controls::Button^ B3_4;
        private: ::Windows::UI::Xaml::Controls::Button^ B4_4;
        private: ::Windows::UI::Xaml::Controls::Button^ B0_3;
        private: ::Windows::UI::Xaml::Controls::Button^ B1_3;
        private: ::Windows::UI::Xaml::Controls::Button^ B2_3;
        private: ::Windows::UI::Xaml::Controls::Button^ B3_3;
        private: ::Windows::UI::Xaml::Controls::Button^ B4_3;
        private: ::Windows::UI::Xaml::Controls::Button^ B0_2;
        private: ::Windows::UI::Xaml::Controls::Button^ B1_2;
        private: ::Windows::UI::Xaml::Controls::Button^ B2_2;
        private: ::Windows::UI::Xaml::Controls::Button^ B3_2;
        private: ::Windows::UI::Xaml::Controls::Button^ B4_2;
        private: ::Windows::UI::Xaml::Controls::Button^ B0_1;
        private: ::Windows::UI::Xaml::Controls::Button^ B1_1;
        private: ::Windows::UI::Xaml::Controls::Button^ B2_1;
        private: ::Windows::UI::Xaml::Controls::Button^ B3_1;
        private: ::Windows::UI::Xaml::Controls::Button^ B4_1;
        private: ::Windows::UI::Xaml::Controls::Button^ B0_0;
        private: ::Windows::UI::Xaml::Controls::Button^ B1_0;
        private: ::Windows::UI::Xaml::Controls::Button^ B2_0;
        private: ::Windows::UI::Xaml::Controls::Button^ B3_0;
        private: ::Windows::UI::Xaml::Controls::Button^ B4_0;
    };
}

